### ISSUE TITLE
双击GUI程序，提示需要安装 .NET Runtime，但安装之后仍无法运行。

### ISSUE THREAD

**Issue by qizaodian** [net2cn/Real-ESRGAN_GUI#1]
系统：Windows 10 专业版 21H2 19044.1586
Real-ESRGAN_GUI：1.0.0.1

双击GUI程序，按照提示安装 .NET Runtime 5.0.15 之后，仍无法运行，继续弹出提示要求安装 .NET Runtime。

尝试重启系统，无效；尝试安装最新的 .NET Runtime 6.0.3，无效。

**Comment by net2cn** [comment]
请尝试安装.NET Desktop Runtime 5.0.15，可以在[这里](https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-5.0.15-windows-x64-installer)找到
还有请确保你下载的是x64版本的Runtime，x86版本的Runtime可能不受支持

**Comment by qizaodian** [comment]
尝试安装 .NET Desktop Runtime 5.0.15 x64，仍无法运行。
继续尝试，打开Windows沙盒，在沙盒里安装 .NET Desktop Runtime 5.0.15 x64，复制 Real-ESRGAN_GUI-1.0.0.1.zip 到沙盒Desktop，解压，运行GUI程序，仍然不行。

**Comment by qizaodian** [comment]
抱歉，我搞错了。我安装的是 .NET Runtime 5.0.15 x64，而不是 .NET Desktop Runtime 5.0.15 x64，现在已经可以运行了。
