### ISSUE TITLE
1.0.0.3 pre 转换的图片变形且有竖条纹

### ISSUE THREAD

**Issue by MeiLaii** [net2cn/Real-ESRGAN_GUI#4]
![image](https://user-images.githubusercontent.com/99824318/166105745-800c8c3f-348b-4d1f-9a61-604eeb7f16b9.png)
**左边是1.0.0.2   右边是1.0.0.3 pre**

![image](https://user-images.githubusercontent.com/99824318/166105797-80338e28-ff45-4d69-b84f-f04a13d84070.png)

**Comment by net2cn** [comment]
介意分享一下原图吗？
你可以通过拖放文件到评论编辑栏来添加附件

**Comment by MeiLaii** [comment]
> 介意分享一下原图吗？ 你可以通过拖放文件到评论编辑栏来添加附件
![ce](https://user-images.githubusercontent.com/99824318/166109607-98b8f01b-f536-4549-a341-50d79a7fdff6.jpg)
我试过其他图也是一样的情况

**Comment by net2cn** [comment]
这个bug是因为对Format24bppRgb的图像处理不当引起的，在预处理过程中原始图像被转换成Format32bppArgb图像了。已在 cae934554b15671863484eed9fb41256575a1ce0 中修复了这一问题。

**Comment by net2cn** [comment]
[1.0.0.3_pre2](https://github.com/net2cn/Real-ESRGAN_GUI/releases/tag/1.0.0.3_pre2)已解决该问题
