### ISSUE TITLE
透明图像转换后的黑块问题

### ISSUE THREAD

**Issue by kongmao45678** [net2cn/Real-ESRGAN_GUI#5]
测试过不少放大软件，对透明图像处理后，通过部份看图软件能看过黑块，比如HD看图。或者导入游戏中能看到。
_黑块的大小根据转换算法不同，区域不同。下图，展示了原图，4P，6B用HD看图软件所产生的区别。6B好很多，但还是周边有黑色部份，导致处理有些图像后，导入游戏会显示出这黑色部份。
![6B](https://user-images.githubusercontent.com/79181884/166132515-5378df49-acbb-4324-b9a6-07117ea4a336.png)
![08fcb3c0b870e61a9fb5e1d1_realesrgan-x4plus](https://user-images.githubusercontent.com/79181884/166132516-0275edff-dbc0-48d8-9cf8-34bd0e7d3b5d.png)
![08fcb3c0b870e61a9fb5e1d1_realesrgan-x4plus_anime_6B](https://user-images.githubusercontent.com/79181884/166132517-9420ffff-7770-4a65-aabe-50aaa620771c.png)
![x4P](https://user-images.githubusercontent.com/79181884/166132520-10aceaad-69a7-43a7-9067-d31a7ebcf510.png)

**Comment by net2cn** [comment]
介意分享一下原图吗？
你可以通过拖放文件到评论编辑栏来添加附件

**Comment by kongmao45678** [comment]
[原图和黑块展示图 .zip](https://github.com/net2cn/Real-ESRGAN_GUI/files/8598374/default.zip)
已上传，正常 打开是透明的看不出问题，得用HD看图软件打开或导入游戏中才能看到。
HD看图软件下载链接：https://pan.baidu.com/s/1e_dbG_8ANFGgDJr7iY8Vug?pwd=0000 
提取码：0000

**Comment by net2cn** [comment]
大概是BICUBIC的artifact，我试试用Real-ESRGAN对alpha通道超分看看效果

**Comment by net2cn** [comment]
破案了，系没有进行premultiplied alpha的锅，commit 172b0d789e4e9cc5b11e20c810bcaaf948846063 修正了这个问题

**Comment by net2cn** [comment]
[1.0.0.3_pre2](https://github.com/net2cn/Real-ESRGAN_GUI/releases/tag/1.0.0.3_pre2)已解决该问题

**Comment by kongmao45678** [comment]
神了，现在就试一下。老是麻烦你……

**Comment by kongmao45678** [comment]
[测试图.zip](https://github.com/net2cn/Real-ESRGAN_GUI/files/8599135/default.zip)
刚测试了一下，还是有黑边哦。

**Comment by net2cn** [comment]
这个就真的是BICUBIC的artifact了，可以通过也使用Real-ESRGAN对alpha通道进行超分，或者将alpha通道向内推进几个像素之类的trick来缓解
也许之后实现了用Lanczos甚至是Edge-directed的重采样算法对alpha通道进行放大可能问题能得到缓解
