### ISSUE TITLE
模型转换

### ISSUE THREAD

**Issue by deism** [net2cn/Real-ESRGAN_GUI#6]
@net2cn 请问在这个app中，如果要挂上自己的onnx文件，用自己数据训练的两倍模型文件，用哪个脚本转换为onnx，是否要加预处理？谢谢！

**Comment by net2cn** [comment]
你可以使用Real-ESRGAN repo里面带的[pytorch2onnx.py](https://github.com/xinntao/Real-ESRGAN/blob/master/scripts/pytorch2onnx.py)脚本来进行转换
推荐在Colab环境下执行转换https://colab.research.google.com/drive/1k2Zod6kSHEvraybHl50Lys0LerhyTMCo?usp=sharing

**Comment by deism** [comment]
谢谢回复，实际上我使用了Real-ESRGAN repo里面带的[pytorch2onnx.py](https://github.com/xinntao/Real-ESRGAN/blob/master/scripts/pytorch2onnx.py)脚本来，对real-esrgan_x2plus进行转换，出现如下报错：
  File "scripts\pytorch2onnx.py", line 7, in <module>
    model.load_state_dict(torch.load('experiments/pretrained_models/RealESRGAN_x2plus.pth')['params_ema'])
  File "E:\anaconda3\envs\aii\lib\site-packages\torch\nn\modules\module.py", line 1483, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for RRDBNet:
        size mismatch for conv_first.weight: copying a param with shape torch.Size([64, 12, 3, 3]) from checkpoint, the shape in current model is torch.Size([64, 3, 3, 3]).
        
        x2的第一层是64,12,3,3，和x4不同，不知如何解决？

**Comment by deism** [comment]
我按照上述操作，发现转换结果和本项目有些区别，我在下图用黄框标出。我用它替换publish-1.0.0.3_pre2中的2倍模型，运行中发生崩溃
![image](https://user-images.githubusercontent.com/6513657/170655961-51fd362e-2a0d-4d91-a028-ab9e2385b212.png)

**Comment by net2cn** [comment]
不好意思，忘记还有一点了，还需将第23行改为
```Python
torch_out = torch.onnx._export(model, x, args.output, input_names=["data"], opset_version=11, export_params=True)
```
才能使得导出的ONNX模型保持与该项目使用的模型输入一致

**Comment by deism** [comment]
改了第23行，还是没有变化。这个差异应该就是 pixel unshuffle 的代码, 可能还有其它设置需要更改

**Comment by net2cn** [comment]
hmmmmmmmmmmmmmm，或许可以试试我当时使用的[转换脚本](https://github.com/net2cn/Real-ESRGAN_GUI/blob/master/scripts/pytorch2onnx.py)
依然是在Colab环境下执行得到的最终转换模型，x2plus的话可能仍要修改RRDBNet的scale参数

**Comment by deism** [comment]
用上述转换脚本，能够生成同样onnx模型文件，非常感谢！
不过经过测试，发现2倍模型,，无论是自带还是我转换的模型，输出结果皆为异常，请见下面x2和x4输出比较。
![image](https://user-images.githubusercontent.com/6513657/170723356-53520321-150f-42c9-bb11-fec259326fc9.png)

输入图像如下：
![90-1](https://user-images.githubusercontent.com/6513657/170724712-a842b46e-31b5-404e-9280-39d3b30a8d07.png)

可能还存在和 pixel shuffle 相关的转换设置要求
